<?php
// Event Guide Module
// $Id: xoops_version.php,v 1.27 2006/02/27 17:32:43 nobu Exp $

$modversion['name'] = _MI_EGUIDE_NAME;
$modversion['version'] = "1.96";
$modversion['description'] = _MI_EGUIDE_DESC;
$modversion['credits'] = "Nobuhiro Yasutomi";
$modversion['author'] = "Nobuhiro Yasutomi";
$modversion['help'] = "help.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "eguide_slogo2.png";
$modversion['dirname'] = "eguide";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "eguide";
$modversion['tables'][1] = "eguide_opt";
$modversion['tables'][2] = "eguide_reserv";
$modversion['tables'][3] = "eguide_category";
$modversion['tables'][4] = "eguide_extent";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][1]=array('file' => 'eguide_index.html',
				  'description' => _MI_EGUIDE_INDEX_TPL);
$modversion['templates'][2]=array('file' => 'eguide_event.html',
				  'description' => _MI_EGUIDE_EVENT_TPL);
$modversion['templates'][3]=array('file' => 'eguide_receipt.html',
				  'description' => _MI_EGUIDE_RECEIPT_TPL);
$modversion['templates'][4]=array('file' => 'eguide_admin.html',
				  'description' => _MI_EGUIDE_ADMIN_TPL);
$modversion['templates'][5]=array('file' => 'eguide_receipt_print.html',
				  'description' => _MI_EGUIDE_RECEIPT_PRINT_TPL);
$modversion['templates'][6]=array('file' => 'eguide_event_print.html',
				  'description' => _MI_EGUIDE_EVENT_PRINT_TPL);
$modversion['templates'][7]=array('file' => 'eguide_item.html',
				  'description' => _MI_EGUIDE_EVENT_ITEM_TPL);
$modversion['templates'][8]=array('file' => 'eguide_confirm.html',
				  'description' => _MI_EGUIDE_EVENT_CONF_TPL);
$modversion['templates'][9]=array('file' => 'eguide_mylist.html',
				  'description' => _MI_EGUIDE_EVENT_LIST_TPL);
// Blocks
$modversion['blocks'][1]=array('file' => "ev_top.php",
			       'name' => _MI_EGUIDE_HEADLINE,
			       'description' => _MI_EGUIDE_HEADLINE_DESC,
			       'show_func' => 'b_event_top_show',
			       'edit_func' => 'b_event_top_edit',
			       'options' => '0|10|19|0',
			       'template' => 'eguide_block_top.html');

$modversion['blocks'][2]=array('file' => "ev_top.php",
			       'name' => _MI_EGUIDE_HEADLINE2,
			       'description' => _MI_EGUIDE_HEADLINE2_DESC,
			       'show_func' => 'b_event_top_show',
			       'edit_func' => 'b_event_top_edit',
			       'options' => '0|10|19|1',
			       'template' => 'eguide_block_top.html');
// Menu
$module_handler =& xoops_gethandler('module');
$module =& $module_handler->getByDirname($modversion['dirname']);

global $xoopsUser;
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_EGUIDE_MYLIST;
$modversion['sub'][1]['url'] = "mylist.php";
if (is_object($module)&&$module->getVar('isactive')) {
    $config_handler =& xoops_gethandler('config');
    $configs =& $config_handler->getConfigsByCat(0, $module->getVar('mid'));
    if (is_object($xoopsUser) &&
	in_array($configs['group'], $xoopsUser->getGroups())) {
	$modversion['sub'][2]['name'] = _MI_EGUIDE_SUBMIT;
	$modversion['sub'][2]['url'] = "admin.php";
    }
    if ($configs['user_notify']) {
	$modversion['sub'][3]['name'] = _MI_EGUIDE_REG;
	$modversion['sub'][3]['url'] = "reserv.php?op=register";
    }
}

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "eguide_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'event.php';
$modversion['comments']['itemName'] = 'eid';

// Config
$modversion['hasconfig'] = 1;
$modversion['config'][]=array('name' => 'group',
			      'title' => '_MI_EGUIDE_POSTGROUP',
			      'description' => '_MI_EGUIDE_POSTGROUP_DESC',
			      'formtype' => 'group',
			      'valuetype' => 'int',
			      'default' => 2);
$modversion['config'][]=array('name' => 'notify',
			      'title' => '_MI_EGUIDE_NOTIFYADMIN',
			      'description' => '_MI_EGUIDE_NOTIFYADMIN_DESC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 1);
$modversion['config'][]=array('name' => 'notify_group',
			      'title' => '_MI_EGUIDE_NOTIFYGROUP',
			      'description' => '_MI_EGUIDE_NOTIFYGROUP_DESC',
			      'formtype' => 'group',
			      'valuetype' => 'int',
			      'default' => 1);
$modversion['config'][]=array('name' => 'auth',
			      'title' => '_MI_EGUIDE_NEEDPOSTAUTH',
			      'description' => '_MI_EGUIDE_NEEDPOSTAUTH_DESC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 0);
$modversion['config'][]=array('name' => 'max_item',
			      'title' => '_MI_EGUIDE_MAX_LISTITEM',
			      'description' => '_MI_EGUIDE_MAX_LISTITEM_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 3);
$modversion['config'][]=array('name' => 'max_list',
			      'title' => '_MI_EGUIDE_MAX_LISTLINES',
			      'description' => '_MI_EGUIDE_MAX_LISTLINES_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 50);
$modversion['config'][]=array('name' => 'max_event',
			      'title' => '_MI_EGUIDE_MAX_EVENT',
			      'description' => '_MI_EGUIDE_MAX_LISTITEM_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 10);
$modversion['config'][]=array('name' => 'show_extents',
			      'title' => '_MI_EGUIDE_SHOW_EXTENTS',
			      'description' => '_MI_EGUIDE_SHOW_EXTENTS_DESC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 1);
$modversion['config'][8]=array('name' => 'user_notify',
			       'title' => '_MI_EGUIDE_USER_NOTIFY',
			       'description' => '_MI_EGUIDE_USER_NOTIFY_DESC',
			       'formtype' => 'yesno',
			       'valuetype' => 'int',
			       'default' => 1);
$modversion['config'][]=array('name' => 'member_only',
			      'title' => '_MI_EGUIDE_MEMBER',
			      'description' => '_MI_EGUIDE_MEMBER_DESC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 0);
$modversion['config'][]=array('name' => 'close_before',
			      'title' => '_MI_EGUIDE_CLOSEBEFORE',
			      'description' => '_MI_EGUIDE_CLOSEBEFORE_DESC',
			      'formtype' => 'text',
			      'valuetype' => 'int',
			      'default' => 60);
$modversion['config'][]=array('name' => 'use_plugins',
			       'title' => '_MI_EGUIDE_PLUGINS',
			       'description' => '_MI_EGUIDE_PLUGINS_DESC',
			       'formtype' => 'yesno',
			       'valuetype' => 'int',
			       'default' => 0);
$modversion['config'][]=array('name' => 'maker_set',
			      'title' => '_MI_EGUIDE_MARKER',
			      'description' => '_MI_EGUIDE_MARKER_DESC',
			      'formtype' => 'textarea',
			      'valuetype' => 'text',
			      'default' => _MI_EGUIDE_MARKER_DEF);
$modversion['config'][]=array('name' => 'use_comment',
			      'title' => '_MI_EGUIDE_COMMENT',
			      'description' => '_MI_EGUIDE_COMMENT_DESC',
			      'formtype' => 'yesno',
			      'valuetype' => 'int',
			      'default' => 1);

?>