<?php
// Event Guide Module
// $Id: xoops_version.php,v 1.22 2005/11/19 08:57:14 nobu Exp $

$modversion['name'] = _MI_EGUIDE_NAME;
$modversion['version'] = "1.901";
$modversion['description'] = _MI_EGUIDE_DESC;
$modversion['credits'] = "Nobuhiro Yasutomi";
$modversion['author'] = "Nobuhiro Yasutomi";
$modversion['help'] = "help.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "eguide_slogo2.png";
$modversion['dirname'] = "eguide";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "eguide";
$modversion['tables'][1] = "eguide_opt";
$modversion['tables'][2] = "eguide_reserv";
$modversion['tables'][3] = "eguide_category";
$modversion['tables'][4] = "eguide_extent";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][1]=array('file' => 'eguide_index.html',
				  'description' => _MI_EGUIDE_INDEX_TPL);
$modversion['templates'][2]=array('file' => 'eguide_event.html',
				  'description' => _MI_EGUIDE_EVENT_TPL);
$modversion['templates'][3]=array('file' => 'eguide_receipt.html',
				  'description' => _MI_EGUIDE_RECEIPT_TPL);
$modversion['templates'][4]=array('file' => 'eguide_admin.html',
				  'description' => _MI_EGUIDE_ADMIN_TPL);
$modversion['templates'][5]=array('file' => 'eguide_receipt_print.html',
				  'description' => _MI_EGUIDE_RECEIPT_PRINT_TPL);
$modversion['templates'][6]=array('file' => 'eguide_event_print.html',
				  'description' => _MI_EGUIDE_EVENT_PRINT_TPL);
// Blocks
$modversion['blocks'][1]=array('file' => "ev_top.php",
			       'name' => _MI_EGUIDE_HEADLINE,
			       'description' => _MI_EGUIDE_HEADLINE_DESC,
			       'show_func' => 'b_event_top_show',
			       'edit_func' => 'b_event_top_edit',
			       'options' => '0|10|19|0',
			       'template' => 'eguide_block_top.html');

$modversion['blocks'][2]=array('file' => "ev_top.php",
			       'name' => _MI_EGUIDE_HEADLINE2,
			       'description' => _MI_EGUIDE_HEADLINE2_DESC,
			       'show_func' => 'b_event_top_show',
			       'edit_func' => 'b_event_top_edit',
			       'options' => '0|10|19|1',
			       'template' => 'eguide_block_top.html');
// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_EGUIDE_SUBMIT;
$modversion['sub'][1]['url'] = "admin.php";
$modversion['sub'][2]['name'] = _MI_EGUIDE_REG;
$modversion['sub'][2]['url'] = "reserv.php?op=register";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "eguide_search";

// Config
$modversion['hasconfig'] = 1;
$modversion['config'][1]=array('name' => 'group',
			       'title' => '_MI_EGUIDE_POSTGROUP',
			       'description' => '_MI_EGUIDE_POSTGROUP_DESC',
			       'formtype' => 'group',
			       'valuetype' => 'int',
			       'default' => 2);
$modversion['config'][2]=array('name' => 'notify',
			       'title' => '_MI_EGUIDE_NOTIFYADMIN',
			       'description' => '_MI_EGUIDE_NOTIFYADMIN_DESC',
			       'formtype' => 'yesno',
			       'valuetype' => 'int',
			       'default' => 1);
$modversion['config'][3]=array('name' => 'auth',
			       'title' => '_MI_EGUIDE_NEEDPOSTAUTH',
			       'description' => '_MI_EGUIDE_NEEDPOSTAUTH_DESC',
			       'formtype' => 'yesno',
			       'valuetype' => 'int',
			       'default' => 0);
$modversion['config'][4]=array('name' => 'max_item',
			       'title' => '_MI_EGUIDE_MAX_LISTITEM',
			       'description' => '_MI_EGUIDE_MAX_LISTITEM_DESC',
			       'formtype' => 'text',
			       'valuetype' => 'int',
			       'default' => 3);
$modversion['config'][5]=array('name' => 'max_event',
			       'title' => '_MI_EGUIDE_MAX_EVENT',
			       'description' => '_MI_EGUIDE_MAX_LISTITEM_DESC',
			       'formtype' => 'text',
			       'valuetype' => 'int',
			       'default' => 10);
$modversion['config'][6]=array('name' => 'user_notify',
			       'title' => '_MI_EGUIDE_USER_NOTIFY',
			       'description' => '_MI_EGUIDE_USER_NOTIFY_DESC',
			       'formtype' => 'yesno',
			       'valuetype' => 'int',
			       'default' => 1);
$modversion['config'][7]=array('name' => 'member_only',
			       'title' => '_MI_EGUIDE_MEMBER',
			       'description' => '_MI_EGUIDE_MEMBER_DESC',
			       'formtype' => 'yesno',
			       'valuetype' => 'int',
			       'default' => 0);

?>